### PR TITLE
New

### PR DESCRIPTION
**Pull request by luisivan**

### CODE REVIEW

**Comment by okhaimie-dev** [comment]
Just went through and this reinforced my understanding of Nation3. I am cutting all my distractions by the end of this year and will choose to focus the bulk of my energy and time to Nation3 beginning 2023.

Love what I have seen so far, y'all are amazing.

**Comment by aahna-ashina** [comment]
> Screenshot 2022-12-09 at 6 55 21 PM

@luisivan I think, eventually, it would make sense to include a link to the [Citizen Directory](https://github.com/nation3/citizen-directory) somewhere in this section.  And each Citizen will be able to put a Twitter link on their profile page if they want to.

The profile URLs will look something like `https://citizens.nation3.org/186`, where the number is the Citizen's passport ID.  Let me know if you want me to change this URL structure.

**Comment by luisivan** [comment]
@okhaimie-dev excited for what's to come! 🚀 

@aahna-ashina that makes total sense 👍

**Comment by okhaimie-dev** [comment]
image

I believe this number of $NATION/ETH liquidity rewards APY is no longer accurate, unless we are reverting back to this. [ Token page ]

**Comment by luisivan** [comment]
@aahna-ashina whenever the citizens directory is ready, just open a PR and let's get it added! 🚀

**Comment by aahna-ashina** [comment]
@luisivan Will do 😄

**Pull request merged**
